### ISSUE TITLE
Support Gnome 48

### ISSUE THREAD

**Issue by bhuvankrishna** [elvetemedve/gnome-shell-extension-system-monitor#104]
Hope Gnome 48 will be supported soon. Thanks.

**Comment by bhuvankrishna** [comment]
I think a simple update of version in metadata should solve the issue.

**Comment by SuggonM** [comment]
Still seeing no issues in GNOME 50. I think even a lazy PR of just bumping the version number should be enough.
